name: "[CD] Upload to pypi"

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: github.repository == 'aws-cloudformation/cfn-lint'
    if: github.repository == 'meeuw/cfn-lint'
    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Download release
        run: |
          gh release download ${{ github.ref_name }}
          mkdir -p dist
          cp cfn_lint-${{ github.ref_name }}.tar.gz cfn_lint-${{ github.ref_name }}-py3-none-any.whl dist/
      #- name: Publish to PyPI
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    user: __token__
      #    password: ${{ secrets.PYPI_API_TOKEN }}
